FROM golang:1.21

RUN apt-get update && apt-get install -y \
    gcc libgl1-mesa-dev xorg-dev x11-apps

WORKDIR /app
COPY . .

RUN go mod init meowclient
RUN go mod tidy

RUN go build -o client main.go

CMD ["./client"]
