server {
    listen 3000;
    server_name localhost;

    location = / {
        return 301 /no-pattern/;
    }

    location /no-pattern/ {
        proxy_pass http://no-pattern:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /pattern/ {
        proxy_pass http://pattern:8082;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
